version: "2"

run:
  timeout: 3m
  modules-download-mode: readonly

linters:
  default: none
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused

formatters:
  enable:
    - gofmt
    - goimports
