repos:
  - repo: https://github.com/Bahjat/pre-commit-golang
    rev: v1.0.3
    hooks:
      - id: gofumpt

  - repo: https://github.com/dnephin/pre-commit-golang
    rev: v0.5.1
    hooks:
        - id: go-vet
        - id: go-imports
        - id: validate-toml
        - id: golangci-lint
        - id: go-unit-tests
        - id: go-mod-tidy
