# Contains deployment configurations
#
# If customizing this file for actual use, while still committing changes, use:
# git update-index --skip-worktree deploy.yaml to remove any future changes, with
# --no-skip-worktree to add things back

devices:
  primary-router:
    address: 10.16.32.1
    port: 12244
    user: $UBQ_USER
    # Either password or keyfile may be specified - keyfile is preferred
    # If both are provided, the password will be used as the passphrase to the keyfile
    password: $UBQ_PASS
    keyfile: $UBQ_KEYFILE

    templatesDir: "./templates"
    configFiles:
      - "config.boot"

    # The path to store the new config file in
    config-file-path: /tmp
    # The path to vyatta-cfg-cmd-wrapper
    # Typically in /opt/vyatta/[s]bin
    configure-script-path: /opt/vyatta/sbin/vyatta-cfg-cmd-wrapper

    # Immediately revert failed changes
    auto-rollback-on-failure: True
    # Schedule reboot after N minutes, to ensure you don't accidentally lose access to the router
    # Can be canceled with `shutdown -c`
    reboot-after-minutes: 5
    # Save config after commit
    # NOT RECOMMENDED - manually validate the config after deploying to ensure there are no flaws
    # This could lock you out of the router!!!
    save-after-commit: False

# Interface settings
logging:
  user: $UBQ_CONFIG_USER
  pass: $UBQ_CONFIG_PASS

git:
  # The ID of the application
  app-id: 95943
  # The main GitHub branch
  primary-branch: main

  private-key-path: ./ubiquiti-config.pem
  # The address for the webserver to listen on
  listen-ip: 0.0.0.0
  # The external URL of the webhook, should match the GitHub app configuration
  webhook-url: https://git.bammeson.com
  # The port to listen on for GitHub webhook stuff
  webhook-port: 54321
  # The secret to use with GitHub webhooks
  webhook-secret: $UBQ_GITHUB_WEBHOOK_SECRET