FROM golang:1.27.1-bookworm
WORKDIR /workspace
COPY go.mod go.sum ./
RUN go mod download
COPY cmd/ ./cmd/
COPY internal/ ./internal/
COPY integration/ ./integration/
CMD ["go", "test", "-count=1", "./..."]
