// Code generated by counterfeiter. DO NOT EDIT.
package configurationfakes

import (
	"sync"

	"github.com/ammesonb/ubiquiti-config-generator/services/configuration"
	"github.com/ammesonb/ubiquiti-config-generator/services/filesystem"
)

type FakeService struct {
	GetDevicesStub        func() []*configuration.DeviceConfig
	getDevicesMutex       sync.RWMutex
	getDevicesArgsForCall []struct {
	}
	getDevicesReturns struct {
		result1 []*configuration.DeviceConfig
	}
	getDevicesReturnsOnCall map[int]struct {
		result1 []*configuration.DeviceConfig
	}
	GetGitConfigStub        func() configuration.GitConfig
	getGitConfigMutex       sync.RWMutex
	getGitConfigArgsForCall []struct {
	}
	getGitConfigReturns struct {
		result1 configuration.GitConfig
	}
	getGitConfigReturnsOnCall map[int]struct {
		result1 configuration.GitConfig
	}
	GetLoggingConfigStub        func() configuration.LoggingConfig
	getLoggingConfigMutex       sync.RWMutex
	getLoggingConfigArgsForCall []struct {
	}
	getLoggingConfigReturns struct {
		result1 configuration.LoggingConfig
	}
	getLoggingConfigReturnsOnCall map[int]struct {
		result1 configuration.LoggingConfig
	}
	LoadStub        func(string, filesystem.Service) error
	loadMutex       sync.RWMutex
	loadArgsForCall []struct {
		arg1 string
		arg2 filesystem.Service
	}
	loadReturns struct {
		result1 error
	}
	loadReturnsOnCall map[int]struct {
		result1 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeService) GetDevices() []*configuration.DeviceConfig {
	fake.getDevicesMutex.Lock()
	ret, specificReturn := fake.getDevicesReturnsOnCall[len(fake.getDevicesArgsForCall)]
	fake.getDevicesArgsForCall = append(fake.getDevicesArgsForCall, struct {
	}{})
	stub := fake.GetDevicesStub
	fakeReturns := fake.getDevicesReturns
	fake.recordInvocation("GetDevices", []interface{}{})
	fake.getDevicesMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeService) GetDevicesCallCount() int {
	fake.getDevicesMutex.RLock()
	defer fake.getDevicesMutex.RUnlock()
	return len(fake.getDevicesArgsForCall)
}

func (fake *FakeService) GetDevicesCalls(stub func() []*configuration.DeviceConfig) {
	fake.getDevicesMutex.Lock()
	defer fake.getDevicesMutex.Unlock()
	fake.GetDevicesStub = stub
}

func (fake *FakeService) GetDevicesReturns(result1 []*configuration.DeviceConfig) {
	fake.getDevicesMutex.Lock()
	defer fake.getDevicesMutex.Unlock()
	fake.GetDevicesStub = nil
	fake.getDevicesReturns = struct {
		result1 []*configuration.DeviceConfig
	}{result1}
}

func (fake *FakeService) GetDevicesReturnsOnCall(i int, result1 []*configuration.DeviceConfig) {
	fake.getDevicesMutex.Lock()
	defer fake.getDevicesMutex.Unlock()
	fake.GetDevicesStub = nil
	if fake.getDevicesReturnsOnCall == nil {
		fake.getDevicesReturnsOnCall = make(map[int]struct {
			result1 []*configuration.DeviceConfig
		})
	}
	fake.getDevicesReturnsOnCall[i] = struct {
		result1 []*configuration.DeviceConfig
	}{result1}
}

func (fake *FakeService) GetGitConfig() configuration.GitConfig {
	fake.getGitConfigMutex.Lock()
	ret, specificReturn := fake.getGitConfigReturnsOnCall[len(fake.getGitConfigArgsForCall)]
	fake.getGitConfigArgsForCall = append(fake.getGitConfigArgsForCall, struct {
	}{})
	stub := fake.GetGitConfigStub
	fakeReturns := fake.getGitConfigReturns
	fake.recordInvocation("GetGitConfig", []interface{}{})
	fake.getGitConfigMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeService) GetGitConfigCallCount() int {
	fake.getGitConfigMutex.RLock()
	defer fake.getGitConfigMutex.RUnlock()
	return len(fake.getGitConfigArgsForCall)
}

func (fake *FakeService) GetGitConfigCalls(stub func() configuration.GitConfig) {
	fake.getGitConfigMutex.Lock()
	defer fake.getGitConfigMutex.Unlock()
	fake.GetGitConfigStub = stub
}

func (fake *FakeService) GetGitConfigReturns(result1 configuration.GitConfig) {
	fake.getGitConfigMutex.Lock()
	defer fake.getGitConfigMutex.Unlock()
	fake.GetGitConfigStub = nil
	fake.getGitConfigReturns = struct {
		result1 configuration.GitConfig
	}{result1}
}

func (fake *FakeService) GetGitConfigReturnsOnCall(i int, result1 configuration.GitConfig) {
	fake.getGitConfigMutex.Lock()
	defer fake.getGitConfigMutex.Unlock()
	fake.GetGitConfigStub = nil
	if fake.getGitConfigReturnsOnCall == nil {
		fake.getGitConfigReturnsOnCall = make(map[int]struct {
			result1 configuration.GitConfig
		})
	}
	fake.getGitConfigReturnsOnCall[i] = struct {
		result1 configuration.GitConfig
	}{result1}
}

func (fake *FakeService) GetLoggingConfig() configuration.LoggingConfig {
	fake.getLoggingConfigMutex.Lock()
	ret, specificReturn := fake.getLoggingConfigReturnsOnCall[len(fake.getLoggingConfigArgsForCall)]
	fake.getLoggingConfigArgsForCall = append(fake.getLoggingConfigArgsForCall, struct {
	}{})
	stub := fake.GetLoggingConfigStub
	fakeReturns := fake.getLoggingConfigReturns
	fake.recordInvocation("GetLoggingConfig", []interface{}{})
	fake.getLoggingConfigMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeService) GetLoggingConfigCallCount() int {
	fake.getLoggingConfigMutex.RLock()
	defer fake.getLoggingConfigMutex.RUnlock()
	return len(fake.getLoggingConfigArgsForCall)
}

func (fake *FakeService) GetLoggingConfigCalls(stub func() configuration.LoggingConfig) {
	fake.getLoggingConfigMutex.Lock()
	defer fake.getLoggingConfigMutex.Unlock()
	fake.GetLoggingConfigStub = stub
}

func (fake *FakeService) GetLoggingConfigReturns(result1 configuration.LoggingConfig) {
	fake.getLoggingConfigMutex.Lock()
	defer fake.getLoggingConfigMutex.Unlock()
	fake.GetLoggingConfigStub = nil
	fake.getLoggingConfigReturns = struct {
		result1 configuration.LoggingConfig
	}{result1}
}

func (fake *FakeService) GetLoggingConfigReturnsOnCall(i int, result1 configuration.LoggingConfig) {
	fake.getLoggingConfigMutex.Lock()
	defer fake.getLoggingConfigMutex.Unlock()
	fake.GetLoggingConfigStub = nil
	if fake.getLoggingConfigReturnsOnCall == nil {
		fake.getLoggingConfigReturnsOnCall = make(map[int]struct {
			result1 configuration.LoggingConfig
		})
	}
	fake.getLoggingConfigReturnsOnCall[i] = struct {
		result1 configuration.LoggingConfig
	}{result1}
}

func (fake *FakeService) Load(arg1 string, arg2 filesystem.Service) error {
	fake.loadMutex.Lock()
	ret, specificReturn := fake.loadReturnsOnCall[len(fake.loadArgsForCall)]
	fake.loadArgsForCall = append(fake.loadArgsForCall, struct {
		arg1 string
		arg2 filesystem.Service
	}{arg1, arg2})
	stub := fake.LoadStub
	fakeReturns := fake.loadReturns
	fake.recordInvocation("Load", []interface{}{arg1, arg2})
	fake.loadMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeService) LoadCallCount() int {
	fake.loadMutex.RLock()
	defer fake.loadMutex.RUnlock()
	return len(fake.loadArgsForCall)
}

func (fake *FakeService) LoadCalls(stub func(string, filesystem.Service) error) {
	fake.loadMutex.Lock()
	defer fake.loadMutex.Unlock()
	fake.LoadStub = stub
}

func (fake *FakeService) LoadArgsForCall(i int) (string, filesystem.Service) {
	fake.loadMutex.RLock()
	defer fake.loadMutex.RUnlock()
	argsForCall := fake.loadArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeService) LoadReturns(result1 error) {
	fake.loadMutex.Lock()
	defer fake.loadMutex.Unlock()
	fake.LoadStub = nil
	fake.loadReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeService) LoadReturnsOnCall(i int, result1 error) {
	fake.loadMutex.Lock()
	defer fake.loadMutex.Unlock()
	fake.LoadStub = nil
	if fake.loadReturnsOnCall == nil {
		fake.loadReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.loadReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeService) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.getDevicesMutex.RLock()
	defer fake.getDevicesMutex.RUnlock()
	fake.getGitConfigMutex.RLock()
	defer fake.getGitConfigMutex.RUnlock()
	fake.getLoggingConfigMutex.RLock()
	defer fake.getLoggingConfigMutex.RUnlock()
	fake.loadMutex.RLock()
	defer fake.loadMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeService) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ configuration.Service = new(FakeService)
