---
cidr: 10.0.12.0/24
authoritative: enable
default-router: 10.0.12.1
dns-server: 10.0.12.1
dns-servers:
  - 8.8.8.8
  - 8.8.4.4
domain-name: internal.home
start: 10.0.12.100
stop: 10.0.12.254
lease: 86400
interface_name: eth1
vif: 20
duplex: auto
speed: auto
...
